User.destroy_all
u1 = User.create :email => 'marco@ga.co', :password => 'chicken', :admin => true
u2 = User.create :email => 'polo@ga.co', :password => "chicken"
puts "#{ User.count } users"

# Dream.destroy_all
# d1 = Dream.create 
# d2 = Dream.create 
# puts "#{ Dream.count } dreams"

Player.destroy_all
p1 = Player.create :name => 'Sakuragi Hanamichi', :position => 'Power Forward', :teamname => 'Shohoku', :playernumber => '10', :description => 'Sakuragi has a habit of making fun of other players by giving nicknames. Infamous for his odd red hair with his great resolve in basketball', :quote => "I'm tensai Sakuragi Hanamichi. I'm going to play basketball, because I'm the best basketball player", :image => 'link'
p2 = Player.create :name => 'Kaede Rukawa', :position => 'Small Forward', :teamname => 'Shohoku', :playernumber => '11', :description => 'Waking Rukawa from a nap is considered unforgivable, since he will almost always automatically beat up the culprit', :quote => "No matter what, I will be #1, and I'll beat anyone who stops me from achieving that", :image => 'link'
p3 = Player.create :name => 'Ryota Miyagi', :position => 'Point Guard', :teamname => 'Shohoku', :playernumber => '7', :description => 'Sakuragi has a habit of making fun of other players by giving nicknames. Infamous for his odd red hair with his great resolve in basketball', :quote => "Keep practicing, never let somebody tell you you're too small or too slow", :image => 'link'
p4 = Player.create :name => 'Hisashi Mitsui', :position => 'Shooting Guard', :teamname => 'Shohoku', :playernumber => '14', :description => 'While his lack of stamina is his main weakness, the great determination and trust for his team is what keeps him going', :quote => "My goal is to lead Shohoku High to dominate the National Championship! And be the best basketball player in Japan!", :image => 'link'
p5 = Player.create :name => 'Takenori Akagi', :position => 'Centre', :teamname => 'Shohoku', :playernumber => '1', :description => 'One of his hobbies is fishing, and he has a taste for lemons (a common compliment to the fish he catches).', :quote => "The one who controls the rebound controls the game	", :image => 'link'
p6 = Player.create :name => 'Akira Sendoh', :position => 'Small Forward/Point Guard', :teamname => 'Ryonan', :playernumber => '7', :description => 'Easygoing, but enjoys challenges. He can score conitnously under pressure until the match is under control. With the trust and support of his teammates and the coach, he can do.', :quote => "Practice real hard if you want to defeat me!", :image => 'link'
p7 = Player.create :name => 'Jun Uozumi', :position => 'Centre', :teamname => 'Ryonan', :playernumber => '4', :description => 'Uozumi often has a very stern personality, and is not likely to lighten up around anyone, regardless of how he feels about them.', :quote => "I'm the Ryonan's Captain Uozumi. It's a pleasure to meet you", :image => 'link'
p8 = Player.create :name => 'Ryoji Ikegami', :position => 'Power Forward', :teamname => 'Ryonan', :playernumber => '5', :description => 'The vice captain of Team Ryonan, his incredible defense skills have led his team to many victories.', :quote => "Keep practicing, never let somebody tell you you're too small or too slow", :image => 'link'
p9 = Player.create :name => 'Hiroaki Koshino', :position => 'Shooting Guard', :teamname => 'Ryonan', :playernumber => '6', :description => 'An expert dribbler who is paired with uekusa Tomoyuki to form a defense combo. His aggressive play play style can inspire his team', :quote => "My goal is to lead Shohoku High to dominate the National Championship! And be the best basketball player in Japan!", :image => 'link'
p10 = Player.create :name => 'Kicchou Fukuda', :position => 'Power Forward', :teamname => 'Ryonan', :playernumber => '13', :description => 'While his lack of stamina is his main weakness, the great determination and trust for his team is what keeps him going', :quote => "The one who controls the rebound controls the game	", :image => 'link'
p11 = Player.create :name => 'Maki Shinichi', :position => 'Point Guard', :teamname => 'Kainan', :playernumber => '4', :description => 'Sakuragi has a habit of making fun of other players by giving nicknames. Infamous for his odd red hair with his great resolve in basketball', :quote => "I'm tensai Sakuragi Hanamichi. I'm going to play basketball, because I'm the best basketball player", :image => 'link'
p12 = Player.create :name => 'Soichiro Jin', :position => 'Shooting Guard', :teamname => 'Kainan', :playernumber => '6', :description => 'Waking Rukawa from a nap is considered unforgivable, since he will almost always automatically beat up the culprit', :quote => "No matter what, I will be #1, and I'll beat anyone who stops me from achieving that", :image => 'link'
p13 = Player.create :name => 'Nobunaga Kiyota', :position => 'Small Forward', :teamname => 'Kainan', :playernumber => '10', :description => 'Sakuragi has a habit of making fun of other players by giving nicknames. Infamous for his odd red hair with his great resolve in basketball', :quote => "Keep practicing, never let somebody tell you you're too small or too slow", :image => 'link'
p14 = Player.create :name => 'Kazuma Takasago', :position => 'Centre', :teamname => 'Kainan', :playernumber => '5', :description => 'While his lack of stamina is his main weakness, the great determination and trust for his team is what keeps him going', :quote => "My goal is to lead Shohoku High to dominate the National Championship! And be the best basketball player in Japan!", :image => 'link'
p15 = Player.create :name => 'Yoshinori Miyamasu', :position => 'Shooting Guard', :teamname => 'Kainan', :playernumber => '15', :description => 'While his lack of stamina is his main weakness, the great determination and trust for his team is what keeps him going', :quote => "The one who controls the rebound controls the game	", :image => 'link'
p16 = Player.create :name => 'Kenji Fujima', :position => 'Point Guard', :teamname => 'Shoyo', :playernumber => '4', :description => 'Sakuragi has a habit of making fun of other players by giving nicknames. Infamous for his odd red hair with his great resolve in basketball', :quote => "I'm tensai Sakuragi Hanamichi. I'm going to play basketball, because I'm the best basketball player", :image => 'link'
p17 = Player.create :name => 'Toru Hanagata', :position => 'Centre', :teamname => 'Shoyo', :playernumber => '5', :description => 'Waking Rukawa from a nap is considered unforgivable, since he will almost always automatically beat up the culprit', :quote => "No matter what, I will be #1, and I'll beat anyone who stops me from achieving that", :image => 'link'
p18 = Player.create :name => 'Misturu Nagano', :position => 'Power Forward', :teamname => 'Shoyo', :playernumber => '7', :description => 'Sakuragi has a habit of making fun of other players by giving nicknames. Infamous for his odd red hair with his great resolve in basketball', :quote => "Keep practicing, never let somebody tell you you're too small or too slow", :image => 'link'
p19 = Player.create :name => 'Kazushi Hasegawa', :position => 'Small Forward', :teamname => 'Shoyo', :playernumber => '6', :description => 'While his lack of stamina is his main weakness, the great determination and trust for his team is what keeps him going', :quote => "My goal is to lead Shohoku High to dominate the National Championship! And be the best basketball player in Japan!", :image => 'link'
p20 = Player.create :name => 'Shoichi Takano', :position => 'Power Forward', :teamname => 'Shokyo', :playernumber => '8', :description => 'While his lack of stamina is his main weakness, the great determination and trust for his team is what keeps him going', :quote => "The one who controls the rebound controls the game	", :image => 'link'
p21 = Player.create :name => 'Kango Murasame', :position => 'Small Forward', :teamname => 'Miuradai', :playernumber => '4', :description => 'Sakuragi has a habit of making fun of other players by giving nicknames. Infamous for his odd red hair with his great resolve in basketball', :quote => "I'm tensai Sakuragi Hanamichi. I'm going to play basketball, because I'm the best basketball player", :image => 'link'
p22 = Player.create :name => 'Tetsuya Naito', :position => 'Power Forward', :teamname => 'Miuradai', :playernumber => '9', :description => 'Waking Rukawa from a nap is considered unforgivable, since he will almost always automatically beat up the culprit', :quote => "No matter what, I will be #1, and I'll beat anyone who stops me from achieving that", :image => 'link'
p23 = Player.create :name => 'Kazuo Araki', :position => 'Point Guard', :teamname => 'Miuradi', :playernumber => '5', :description => 'Sakuragi has a habit of making fun of other players by giving nicknames. Infamous for his odd red hair with his great resolve in basketball', :quote => "Keep practicing, never let somebody tell you you're too small or too slow", :image => 'link'
p24 = Player.create :name => 'Tatsumasa Oda', :position => 'Centre', :teamname => 'Takezono', :playernumber => '9', :description => 'While his lack of stamina is his main weakness, the great determination and trust for his team is what keeps him going', :quote => "My goal is to lead Shohoku High to dominate the National Championship! And be the best basketball player in Japan!", :image => 'link'
p25 = Player.create :name => 'Tomokazu Godai', :position => 'Shooting Guard', :teamname => 'Tsukubu', :playernumber => '4', :description => 'While his lack of stamina is his main weakness, the great determination and trust for his team is what keeps him going', :quote => "The one who controls the rebound controls the game	", :image => 'link'

puts "#{ Player.count } player"

Move.destroy_all
m1 = Move.create :name => 'Sakuragi Dunk', :category => 'Ultimate', :position => 'Power Forward', :description => 'The player jumps into the air from the free throw line, glides and completes the dunk', :image => 'link'
m2 = Move.create :name => 'Flying Rebound', :category => 'Defense, Rebound', :position => 'Power Forward', :description => 'The player has incredible balances that allows him to tilt his body at such a large angle to get the rebound from further distance', :image => 'link'
m3 = Move.create :name => 'Layup FTW', :category => 'Offense, Layup', :position => 'Power Forward', :description => 'The player uses the Layup FTW he just learned to put the ball into the basket steadily', :image => 'link'
m4 = Move.create :name => 'Super Acceleration', :category => 'Trick, Speed Up', :position => 'Power Forward', :description => "The player's excellent physical quality enables him to sprint superfast", :image => 'link'
m5 = Move.create :name => 'Hua Hua Defense', :category => 'Defense, Jam', :position => 'Power Forward', :description => 'The player stretches out his arms and swings rapidy to defend like a wall', :image => 'link'
m6 = Move.create :name => 'Diving Catch', :category => 'Defensee, Pick Up', :position => 'Power Forward', :description => 'The player is very determined and driven. He will agilely pounce on the loos ball for possession.', :image => 'link'
m7 = Move.create :name => '2 Hand Layup', :category => 'Ultimate', :position => 'Small Forward', :description => 'The player jumps towards teh basket for a slam dunk. When someone attempts to block, he will agiely change hand and make a driving layup instead.', :image => 'link'
m8 = Move.create :name => 'Post-up Drive', :category => 'Trick, Drive', :position => 'Small Forward', :description => 'The player dribbles the ball behind the back to the other side to get past the defender.', :image => 'link'
m9 =  Move.create :name => 'Pull-up Shot', :category => 'Offense, Shoot', :position => 'Small Forward', :description => 'When the player is driving, he will suddnely stop to do a crossover, pulling away from the Ribal and completing a jump shot', :image => 'link'
m10 = Move.create :name => 'Elegant Tip-in', :category => 'Offense, Tip-in', :position => 'Small Forward', :description => "When a teammate's shot bounces off, the player will jump up and tip the ball into the basket elegantly ", :image => 'link' 
m11 = Move.create :name => 'Nimble Steal', :category => 'Defense, Steal', :position => 'Small Forward', :description => "The player quickly snataches the ball from the Rival's hand and jumps up to slap the ball to the attacking direction", :image => 'link' 
m12 = Move.create :name => 'Air Walk', :category => 'Offense, Dunk', :position => 'Small Forward', :description => 'The player leaps a great distance and dunks in the classic fashion of Jordan', :image => 'link' 
m13 = Move.create :name => 'Ultimate Speed', :category => 'Ultimate', :position => 'Point Guard', :description => 'The player eneter the Ultimate Speed status, increasing his speed greatly, lasting for 30 seconds', :image => 'link' 
m14 = Move.create :name => 'Pump Fake Layup', :category => 'Offense, Layup', :position => 'Point Guard', :description => 'The player uses deceptive movement before attempting layup making it hard for the marker to guard him.', :image => 'link' 
m15 = Move.create :name => 'Running Steal', :category => 'Defense, Steal', :position => 'Point Guard', :description => 'The player moves forward fast and quickly steals the ball from the Rvial when passing by.', :image => 'link' 
m16 = Move.create :name => 'Fast Drive', :category => 'Trick, Drive', :position => 'Point Guard', :description => 'When the player is handling the ball and someone is trying to stop him, he can change the direction and increase his movement speed to start driving.', :image => 'link' 
m17 = Move.create :name => 'Shadow Steal', :category => 'Passive, Intercept', :position => 'Point Guard', :description => 'The player is so fast that he is like a phantom. He suddenly appears in front of the Rival that is about to catch a ball and intercepts it', :image => 'link' 
m18 = Move.create :name => 'Fast Pass', :category => 'Trick, Pass', :position => 'Point Guard', :description => 'When the player is handling the ball, he will shakes his wrist slightly to quickly pass the ball to a teammate', :image => 'link' 
m19 = Move.create :name => 'MVP Roll Back', :category => 'Ultimate', :position => 'Shooting Guard', :description => 'When the player regains his MVP status, he will obtain the Fast Dash and Perfect Shot skills in 30 seconds.', :image => 'link' 
m20 = Move.create :name => 'Step-back shot', :category => 'Offense, 3 Pointer', :position => 'Shooting Guard', :description => 'The player suddenly steps back while driblling, creating space for a shot.', :image => 'link' 
m21 = Move.create :name => 'Horizontal Drive', :category => 'Trick, Drive', :position => 'Shooting Guard', :description => 'The player turns sideaway and loses the defender, creating space for a shot.', :image => 'link' 
m22 = Move.create :name => 'Driving Shot', :category => 'Offense, Shoot', :position => 'Shooting Guard', :description => 'The player takes a jump shot while dribbling left and right, making the shot harder for the marker to block.', :image => 'link' 
m23 = Move.create :name => 'Diving Pass', :category => 'Trick, Pick Up', :position => 'Shooting Guard', :description => 'When the player dives to save the ball, he will quickly pass it to the teammate behind him after securing the ball', :image => 'link' 
m24 = Move.create :name => 'Fadeaway 3PL', :category => 'Offense, 3 Pointer', :position => 'Shooting Guard', :description => 'The player makes a very difficult fade away shot outside the 3 point-line', :image => 'link' 
m25 = Move.create :name => 'Akagi Dunk', :category => 'Ultimate', :position => 'Centre', :description => 'The player jumps into the air, breaking through all defenses and dunking like a powerful gorilla.', :image => 'link' 
m26 = Move.create :name => 'Fly Slap', :category => 'Defense, Block', :position => 'Centre', :description => "The player uses the fly slap skill and slaps the Rival's shot", :image => 'link' 
m27 = Move.create :name => 'Fancy Footwork', :category => 'Offense, Shoot', :position => 'Centre', :description => 'The players performs the Fancy Footwork to lose the defender and complete the shot.', :image => 'link' 
m28 = Move.create :name => 'Akagi Rebound', :category => 'Defense, Rebound', :position => 'Centre', :description => 'The player grabs the rebound with his gorilla-level body.', :image => 'link' 
m29 = Move.create :name => 'Textbook Box Out', :category => 'Defense, Box Out', :position => 'Centre', :description => "The player's textbook boxing out technique and he is almost invincible when doing it/", :image => 'link' 
m30 = Move.create :name => 'Alley-One', :category => 'Offense, Dunk', :position => 'Centre', :description => 'The player jumps high, catches the pass from any teammate 2-8 meters away and slam the ball into the basket.', :image => 'link' 
m31 = Move.create :name => 'Turnaround Dunk', :category => 'Ultimate', :position => 'Small Forward/Point Guard', :description => 'The player dribbles the ball and turns quickly to lose the defender and complete a dunk.', :image => 'link' 
m32 = Move.create :name => 'Jelly Layup', :category => 'Offense, Layup', :position => 'Small Forward/Point Guard', :description => 'In forward stance, the player jumps in the form of jelly, layup and completes the layup in a flash, making it diffcult to block.', :image => 'link' 
m33 = Move.create :name => 'Perfect Pass', :category => 'Trick, Pass', :position => 'Small Forward/Point Guard', :description => 'In guard stance, the player passes the ball to a teammate he faces with an unexpected move.', :image => 'link' 
m34 = Move.create :name => 'Fast Break', :category => 'Trick, Drive', :position => 'Small Forward/Point Guard', :description => 'In forward stance, the player dribbles and sways like a phantom, making his movements difficult to capture.', :image => 'link' 
m35 = Move.create :name => 'Step Back', :category => 'Offense, Shoot', :position => 'Small Forward/Point Guard', :description => 'The player dribbles behind and fades away quickly. He will receive the ball in the air and finish the jump shot right away.', :image => 'link'
m36 = Move.create :name => 'Flying Block', :category => 'Defense, Block', :position => 'Small Forward/Point Guard', :description => "In guard stance, the player uses his keen preception to leap and block the Rival'shot.", :image => 'link' 
m37 = Move.create :name => 'Catch and Block', :category => 'Ultimate', :position => 'Centre', :description => "The player open his arms and jumps up to grab the Rival's shot in hand", :image => 'link' 
m38 = Move.create :name => 'Block by Long Arms', :category => 'Defense, Block', :position => 'Centre', :description => "The player's extremely long arms grand him a large blocking area so he can easily block a Rival's shot.", :image => 'link'
m39 = Move.create :name => 'Both Hands Dunk', :category => 'Defense, Drive', :position => 'Centre', :description => 'The player leaps high in the air and slam-dunks forcefully with both hands.', :image => 'link' 
m40 = Move.create :name => 'Rebound', :category => 'Defense, Rebound', :position => 'Centre', :description => "The player's strong wil helps him get more rebounds.", :image => 'link' 
m41 = Move.create :name => 'Ape King', :category => 'Passive, Context', :position => 'Centre', :description => "The player's size make him harder to be moved by the Rival in post-up physical contests", :image => 'link' 
m42 = Move.create :name => 'Dunk Pass', :category => 'Trick, Pass', :position => 'Centre', :description => 'The player pretends toe peform slam dunk, changing gesture in midair and passing the ball to a teammate within range.', :image => 'link' 
m43 = Move.create :name => 'Clutch Steal', :category => 'Ultimate', :position => 'Power Forward', :description => 'The player approaches the handler secrely and quickly steals the ball from his Rival.', :image => 'link' 
m44 = Move.create :name => 'Box Out', :category => 'Defense, Screen', :position => 'Power Forward', :description => "The player's expereince will help him predict the Rival's movement, so he can stop the Rival ahead of time.", :image => 'link' 
m45 = Move.create :name => 'Perfect Defense', :category => 'Defense', :position => 'Power Forward', :description => "When a Rival is inside the player's zone, his perfect defense will pressure the Rival greatly and make it hard for the Rival to drive or shoot", :image => 'link' 
m46 = Move.create :name => 'Shot Fake', :category => 'Offense, Shoot', :position => 'Power Forward', :description => 'The player fakes a shot to make the Rival jump and makes a jump shot.', :image => 'link' 
m47 = Move.create :name => 'Speed Steal', :category => 'Trick, Steal', :position => 'Power Forward', :description => 'The player finds the right time to steal the ball when the Rival is preparing for a basic shot.', :image => 'link' 
m48 = Move.create :name => 'Blind Block', :category => 'Defense, Block', :position => 'Power Forward', :description => "When the player is having trouble blocking a front shot, he will use his palm to block the Rival's sight, owering the chance of his Rival making the shot.", :image => 'link' 
m49 = Move.create :name => 'Euro-step Layup', :category => 'Ultimate', :position => 'Shooting Guard', :description => 'The player makes does a euro step to lose the defener and completes a layup.', :image => 'link'
m50 = Move.create :name => 'Cross Drive', :category => 'Trick, Drive', :position => 'Shooting Guard', :description => 'The player makes sudden cross-leg dribble to penetrate from one side.', :image => 'link' 
m51 = Move.create :name => 'Fade Away Shot', :category => 'Offense, Shoot', :position => 'Shooting Guard', :description => 'The player fades away to dodge the block and completes the shot.', :image => 'link' 
m52 = Move.create :name => 'Driving Pass', :category => 'Trick, Pass', :position => 'Shooting Guard', :description => 'When driving, the player can surprise the teammate and pass the ball to a teammate', :image => 'link' 
m53 = Move.create :name => 'Great Fighter', :category => 'Passive, Defense', :position => 'Shooting Guard', :description => 'When the Rival tries to drop the player, there is a chance that he will remain in his position to keep defending.', :image => 'link' 
m54 = Move.create :name => 'Break Layup', :category => 'Offense, Layup', :position => 'Shooting Guard', :description => 'The player jumps while driving and changes hand in midair to avoid being blocked and complete the layup.', :image => 'link' 
m55 = Move.create :name => 'Alley-oop', :category => 'Ultimate', :position => 'Power Forward', :description => "The player jumps into the air and catches his teammate's pass to complete the Super Alley-oop.", :image => 'link' 
m56 = Move.create :name => 'Catch & Jump Shoot', :category => 'Offense, Shoot', :position => 'Power Forward', :description => 'When the player receives the ball, he will turn around to move away from the defender and jump to complete the shot.', :image => 'link' 
m57 = Move.create :name => 'Catch & Break', :category => 'Trick, Drive', :position => 'Power Forward', :description => 'When the player receives the ball, he will turn around and start driving, so it will be hard for the Rival to catch up.', :image => 'link' 
m58 = Move.create :name => 'High Layup', :category => 'Offense, Layup', :position => 'Power Forward', :description => 'The player throws the ball high to do a lob shot that is hard to block and completes the layup.', :image => 'link' 
m59 = Move.create :name => 'Offensive Rebound', :category => 'Offense, Rebound', :position => 'Power Forward', :description => 'When the player is handling an offensive rebound, he will suddenly jump up to grab the rebound in front of him.', :image => 'link' 
m60 = Move.create :name => 'More Cheers', :category => 'Passive, Shoot', :position => 'Power Forward', :description => 'The player wants more people to cheer for him. His scoring abilities will increase as he scores more points', :image => 'link' 
m61 = Move.create :name => 'Emperor Sense', :category => 'Ultimate', :position => 'Point Guard', :description => "The player's emperor-like sense helps him to observe the whole count, so he can find the best moment to enhance his skill talent.", :image => 'link' 
m62 = Move.create :name => 'Fast Break', :category => 'Trick, Drive', :position => 'Point Guard', :description => "When the player is ready to drive, he will his body as fas as he can and suddenly drive past his Rival from the side. Emperor Quick Shot. The player's emperor sense helps him find the chance to break the Rival's ankle. He can then turn around right away and finish the shot.", :image => 'link' 
m63 = Move.create :name => 'Fast Shoot', :category => 'Offense, Shoot', :position => 'Point Guard', :description => "The player jumps quickly and finishes the shot using the textbook shooting form. Emperor Forced Shot. The player's emperor sense helps him predict the Rival's block. His strong body can withstand the body contact, interrupt the block, and shoot the ball again.", :image => 'link' 
m64 = Move.create :name => 'Fast Steal', :category => 'Defense, Steal', :position => 'Point Guard', :description => "The player uses a nimble movement to steal the Rival's ball when the Rival is not paying attention. Emperor Quick Steal. The player's emperor sense helps him predict the Rival's driving in a 2-meter range. he can then lower his body to catch up and steal the ball from the Rival", :image => 'link' 
m65 = Move.create :name => 'Fast Block', :category => 'Defense, Block', :position => 'Point Guard', :description => "When the Rival tries to do a laup or dunk, the player will suddenly appear in front of the Rival and block the shot. Emperor Reverse. The player's emperor sense helps him notice that the Rival is swithcing the move. His incredible body control can help him complete a recerse block in the air.", :image => 'link' 
m66 = Move.create :name => 'Fast Pass', :category => 'Trick, Pass', :position => 'Point Guard', :description => "When the player is suing the Blink Dirve, he jumps up and passes the ball to a teammate in range. Emperor Pass. The player's Emperor Sense can help him observe the court, so when he is using the Phantom crossover Jumper, he can directly pass the ball to a teammate.", :image => 'link' 
m67 = Move.create :name => 'Time Freeze Shot', :category => 'Ultimate', :position => 'Shooting Guard', :description => "The player's moves are so smooth that it loooks like the time is freezing for other players, and he is the only one shooting.", :image => 'link' 
m68 = Move.create :name => "Jin's Zone", :category => 'Passive, Offense', :position => 'Shooting Guard', :description => 'After the player makes a 3-pointer, he will leave a mark on the floor. Players inside teh range of the mark will have a higher chance of making 3-point shots, up to 2 marks can appear on the floor at the same time.', :image => 'link' 
m69 = Move.create :name => 'Three-point at long ranges', :category => 'Offense, 3-Pointer', :position => 'Shooting Guard', :description => "The player's incredible range gives him the ability to charge and shoot a 3 with high accuracy far from the 3-point line.", :image => 'link' 
m70 = Move.create :name => 'Catch & Shoot', :category => 'Offense, 3 pointer', :position => 'Shooting Guard', :description => 'The player gets ready to receive the ball outside the 3-point line. He will jump up right after receiving the ball and copmlete the 3-point shot.', :image => 'link' 
m71 = Move.create :name => 'Break & Fast Shot', :category => 'Offense, Shoot', :position => 'Shooting Guard', :description => "The player drives to the side quickly. He will jump to complete the shot after avoiding the Rival's defense.", :image => 'link' 
m72 = Move.create :name => 'Catch & Pass', :category => 'Trick, Pass', :position => 'Shooting Guard', :description => 'The player uses himself as the bait. When he receives the ball, he will pass the ball to the teammate in the front and create a scoring opportunity for the teammate.', :image => 'link' 
m73 = Move.create :name => 'Back Dunk Shot', :category => 'Ultimate', :position => 'Small Forward', :description => 'The player leaps from the bottom line and completes a high difficulty reverse dunk from the other side.', :image => 'link' 
m74 = Move.create :name => 'Jump & Block', :category => 'Defense, Block', :position => 'Small Forward', :description => "The player's superior agility and jump give him the ability to block like the Jumpman.", :image => 'link' 
m75 = Move.create :name => 'Step Back Drive', :category => 'Trick, Drive', :position => 'Small Forward', :description => 'The player steps back and charges. His speed suddenly increases to help him drive past the Rival directly.', :image => 'link' 
m76 = Move.create :name => 'Catch & Lay-up Shot', :category => 'Offense, Layup', :position => 'Small Forward', :description => 'When the player recevies the ball, he throws it up and completes the layup.', :image => 'link' 
m77 = Move.create :name => 'Fast dunk', :category => 'Offense, Dunk', :position => 'Small Forward', :description => 'The player jumps into the air and completes a dunk that is too complete of his size.', :image => 'link' 
m78 = Move.create :name => "Kiyota's Stop", :category => 'Trick, Dash', :position => 'Small Forward', :description => 'The player is a nimble like a monkey and he can jump a long distance while leaping.', :image => 'link' 
m79 = Move.create :name => 'Game-deciding rebound', :category => 'Ultimate', :position => 'Centre', :description => 'The player charges for a short preiof and jumps into the air to grab the important rebound with the will to end the match.', :image => 'link' 
m80 = Move.create :name => 'Fake & Layup', :category => 'Offense, Layup', :position => 'Centre', :description => 'The player tirkcs the Rival with a fake move and turns around to jump to the side, completing a high difficulty hook layup.', :image => 'link' 
m81 = Move.create :name => 'Catch & Dunk', :category => 'Offense, Dunk', :position => 'Centre', :description => 'When the player receives the ball, he will jump right away to complete a two-handed slam.', :image => 'link' 
m82 = Move.create :name => 'Super pick-and-roll', :category => 'Trick, Pick & Roll', :position => 'Centre', :description => "The player's incredible Pick and Roll skill cann help him block the Rival easily, creating shooting space for his teammate.", :image => 'link' 
m83 = Move.create :name => 'Fast Box Out', :category => 'Defense, Box Out', :position => 'Centre', :description => 'When the player steps forawrd to box out but he is still behind the Rival, there is a chance that he will move to the fount and take the advantaged position.', :image => 'link' 
m84 = Move.create :name => 'Nice Defense', :category => 'Defense', :position => 'Centre', :description => "The player coruches and raises his arms to befend. He can stop the Rival from driving in and intercpets the Rival's shoothing path.", :image => 'link' 
m85 = Move.create :name => '3-pointer Sniper', :category => 'Ultimate', :position => 'Shooting Guard', :description => "The player takes aim at the basket and shoots the ball with prcision. If you use it while open, then it should put 3 points on the scoreboard. If there's interference, then it will be called.", :image => 'link' 
m86 = Move.create :name => 'Swift Sprint', :category => 'Trick, Speed Up', :position => 'Shooting Guard', :description => 'The plyaer takes advantage of his size to decrease collisions with others and increas his Speed.', :image => 'link' 
m87 = Move.create :name => 'Set Shot', :category => 'Offense, Shoot', :position => 'Shooting Guard', :description => 'The player sets and aims at the basket, then jumps and takes the shot.', :image => 'link' 
m88 = Move.create :name => 'All-out Defense', :category => 'Defense', :position => 'Shooting Guard', :description => "The player goes all out each time he's on defense to ensure that Rivals have as much trouble Driving and Shooting as possible.", :image => 'link' 
m89 = Move.create :name => 'Step Back Drive', :category => 'Trick, Drive', :position => 'Shooting Guard', :description => 'The player stores energy then Step Back and Drives.', :image => 'link' 
m90 = Move.create :name => 'Precise Calculation', :category => 'Passive, Energy', :position => 'Shooting Guard', :description => 'The player precisely calculates every seond of every game, thus increasing his Energy Recovery Speed.', :image => 'link' 
m91 = Move.create :name => 'Green Light', :category => 'Ultimate', :position => 'Point Guard', :description => 'When getting excited, the player is like a green lantern moving around the court. He gains Light-spped Dribble and Phantom Drive-in abilities for 10 s.', :image => 'link' 
m92 = Move.create :name => 'Step Shot', :category => 'Offense, Shoot', :position => 'Point Guard', :description => 'The player hop-steps foward and shoots at changeable timing, making it hard for the defender to block.', :image => 'link' 
m93 = Move.create :name => 'Lane Steal', :category => 'Trick, Steal', :position => 'Point Guard', :description => "The player can steal the Rival's ball with a sneak deflection in the lane.", :image => 'link' 
m94 = Move.create :name => 'Quick Catch & Shot', :category => 'Offense, Shoot', :position => 'Point Guard', :description => 'The player gets ready for ashot. He will shoot immediately after he catches the pass within a certain range.', :image => 'link' 
m95 = Move.create :name => 'Pump Fake', :category => 'Trick, Pass', :position => 'Point Guard', :description => 'The player suddenly changes gesture while performing mid-range shot and passes the ball to a teammate within range.', :image => 'link' 
m96 = Move.create :name => 'Step Back Shot', :category => 'Offense, Shoot', :position => 'Point Guard', :description => 'The player steps back and amkes a fadeaway shot, making it very difficult for the Rival to block.', :image => 'link' 
m97 = Move.create :name => 'Fadeaway Shot', :category => 'Ultimate', :position => 'Centre', :description => 'The player steps back and jumps to complete a fade away shot that is ahrd to block and will never miss.', :image => 'link'
m98 = Move.create :name => 'Turnaround Shot', :category => 'Offense, Shoot', :position => 'Centre', :description => 'Teh player jumps up to complete a floater while turning around to give the Rival a hard time.', :image => 'link'
m99 = Move.create :name => 'Step Break', :category => 'Trick, Drive', :position => 'Centre', :description => 'Teh player uses his nimble footwork to step forward and lose the defender.', :image => 'link'
m100 = Move.create :name => 'Fade Away Shot', :category => 'Offense, Shoot', :position => 'Centre', :description => 'The player fades away to dodge the block and complete the shot.', :image => 'link'
m101 = Move.create :name => 'Turnaround Dunk', :category => 'Offense, Dunk', :position => 'Centre', :description => 'The player gets ready to receive the ball in the paint. He will turn around and complete the dunk right after receiving the pass.', :image => 'link'
m102 = Move.create :name => 'Death & Rebound', :category => 'Defense, Rebound', :position => 'Centre', :description => "With the player's nimble footwork, he will start running so he can grab a rebound that is far from him.", :image => 'link'
m103 = Move.create :name => 'Windmill Layup', :category => 'Ultimate', :position => 'Power Forward', :description => 'The player jumps forward with the ball and peform a windmill layup, which is difficult to block.', :image => 'link'
m104 = Move.create :name => 'Quick Catch to Layup', :category => 'Offense, Layup', :position => 'Power Forward', :description => 'The player stands still and prepares himself to jump forward and peform a lyup after getting the ball.', :image => 'link'
m105 = Move.create :name => 'Two-Handed Suppression Block', :category => 'Defenese, Block', :position => 'Power Forward', :description => 'Faced when a rival trying a layup or slam dunkn, the player jumps to block with both hands.', :image => 'link' 
m106 = Move.create :name => 'Low Post Box Out', :category => 'Trick, Box Out', :position => 'Power Forward', :description => 'The player is alble to move forward and backward faster while boxing out in a low post.', :image => 'link' 
m107 = Move.create :name => 'One-Handed Block', :category => 'Trick, Steal', :position => 'Power Forward', :description => 'The player may intercept the ball with one hand when a rival is asking for ball.', :image => 'link' 
m108 = Move.create :name => 'Tight Mark', :category => 'Defense', :position => 'Power Forward', :description => 'The player tightly marks the rival with the ball, making it difficult for the rival to drive past him or break his ankle.', :image => 'link' 
m109 = Move.create :name => 'Volleyball Block', :category => 'Ultimate', :position => 'Small Forward', :description => 'The player jumps high and surprises the Rival with a super block in the form of a volleyball smash.', :image => 'link' 
m110 = Move.create :name => 'Fast Block', :category => 'Defense, Block', :position => 'Small Forward', :description => "As long as the player is inside the shooter's defense range, he will jump up like lightning and block the Rival's shot.", :image => 'link' 
m111 = Move.create :name => 'Stepback Shoot', :category => 'Offense, Shoot', :position => 'Small Forward', :description => 'The player gets ready to catch the ball. He will step back right after receiving the ball and complete the shot.', :image => 'link'
m112 = Move.create :name => 'Strive Dash', :category => 'Trick, Speed Up', :position => 'Small Forward', :description => 'The player will accelerate, chase down the Rival, and give the Rival a hard time.', :image => 'link' 
m113 = Move.create :name => 'Guard Man', :category => 'Passive, Intercept', :position => 'Small Forward', :description => 'When the player is close to the targetm he will have a higher chance of stopping the target from receiving the ball.', :image => 'link' 
m114 = Move.create :name => 'Fast Shoot', :category => 'Offense, Shoot', :position => 'Small Forward', :description => 'The player jumps up without giving any notice and completes the shot with the speed of lightning.', :image => 'link' 
m115 = Move.create :name => 'Forward Runner', :category => 'Ultimate', :position => 'Power Forward', :description => 'The player drives forward with the ball, taking the opportunity to make a runner.', :image => 'link'
m116 = Move.create :name => 'Back Ball-Keep', :category => 'Kick, Ball Keep', :position => 'Power Forward', :description => 'The player enter the Back Ball-Keep statys, making it difficult for opponenets to do close defence.', :image => 'link'
m117 = Move.create :name => 'Flying Tip-in', :category => 'Offense, Tip-in', :position => 'Power Forward', :description => 'The player jumps up, siwtches hands to catch a rbound in the air, then takes a shot.', :image => 'link'
m118 = Move.create :name => 'Crossover Jumper', :category => 'Trick, Shoot', :position => 'Power Forward', :description => 'The player leaps forward, jumping over a defender, then peforms a jump shot.', :image => 'link' 
m119 = Move.create :name => 'Agile Cover', :category => 'Defense, Block', :position => 'Power Forward', :description => 'Faced when an opponent layup or slam dunk, the player peforms an agile jump to block.', :image => 'link'
m120 = Move.create :name => 'Step Back Catch', :category => 'Offense, Shoot', :position => 'Power Forward', :description => 'When a teammate passes the ball, the player peforms a step back move to pull away form an opponent before catching, then jumps to take a shot.', :image => 'link'
m121 = Move.create :name => 'Windmill Dunk', :category => 'Ultimate', :position => 'Small Forward', :description => 'The player draws a large arc in the air and completes a difficult windmill dunk.', :image => 'link' 
m122 = Move.create :name => 'Fast Break Dunk', :category => 'Offense, Dunk', :position => 'Small Forward', :description => 'The player drives and loses his defender to complete a dunk directly.', :image => 'link' 
m123 = Move.create :name => 'Tip Shot', :category => 'Offense, Tip-in', :position => 'Small Forward', :description => 'When a teammate misses a shot, the player will jump to tip the ball in from the low post.', :image => 'link'
m124 = Move.create :name => 'Catch & Turnback', :category => 'Trick, Drive', :position => 'Small Forward', :description => 'When the player receives the ball, he will suddenly turn around to drive in and create space between him and the Rival.', :image => 'link'
m125 = Move.create :name => 'Dribble Forward', :category => 'Trick, Speed Up', :position => 'Small Forward', :description => 'When the player gets the ball, his dribbling speed is drastically increased for 2 s.', :image => 'link'
m126 = Move.create :name => 'Run & Block', :category => 'Defense, Block', :position => 'Small Forward', :description => 'The player accelerates and jumps up to block an Rival that is shooting from the far side.', :image => 'link'
m127 = Move.create :name => 'Euro Step and Dunk', :category => 'Ultimate', :position => 'Power Forward', :description => 'Teh player does a euro step to lsoe the defender and jumps to complete a dunk.', :image => 'link'
m128 = Move.create :name => 'Interception', :category => 'Passive, Intercept', :position => 'Power Forward', :description => 'The player watches for an opportunity to intercept the ball with a huge stride forward.', :image => 'link' 
m129 = Move.create :name => 'Post Up', :category => 'Trick, Drive', :position => 'Power Forward', :description => "The player's post-up is like a tank crushing into the lane.", :image => 'link'
m130 = Move.create :name => "Naito's Dash", :category => 'Trick, Speed Up', :position => 'Power Forward', :description => 'As the forward in the football team, when the player starts charging, he will dash at full speed.', :image => 'link' 
m131 = Move.create :name => 'Two-Handed Axe', :category => 'Offense, Dunk', :position => 'Power Forward', :description => 'Teh player grabs the ball with both hands and jumps into the air, dunking the ball into the basket like an axe.', :image => 'link' 
m132 = Move.create :name => 'Wild Block', :category => 'Defense, Block', :position => 'Power Forward', :description => "The player jumps up like a beast to slap away the Rival's shot in a rude away.", :image => 'link' 
m133 = Move.create :name => 'Step Shot', :category => 'Ultimate', :position => 'Point Guard', :description => 'The player rapidly hop-steps sideaways and makes space for a jump shot.', :image => 'link'
m134 = Move.create :name => 'Break Shot', :category => 'Offense, Shoot', :position => 'Point Guard', :description => 'The player dribbles forward rapidly to get past the defender for a jump shot.', :image => 'link'
m135 = Move.create :name => 'Diving Catch', :category => 'Trick, Pick Up', :position => 'Point Guard', :description => 'The player will directly pounce on the loose ball, reaching it faster than the Rival.', :image => 'link' 
m136 = Move.create :name => 'Powerful Pass', :category => 'Trick, Pass', :position => 'Point Guard', :description => 'The player hurts the ball at incredible speed to a teammate within 10 metres.', :image => 'link'
m137 = Move.create :name => 'Back Steal', :category => 'Trick, Steal', :position => 'Point Guard', :description => 'When the player is behind the ball carrier, he will use more hidden moves to steal the ball.', :image => 'link'
m138 = Move.create :name => 'Fake & Pass', :category => 'Trick, Pass', :position => 'Point Guard', :description => 'The player pretends to peform mid-range shot and passes the ball to a teammate within range.', :image => 'link'
m139 = Move.create :name => 'Still Moment', :category => 'Ultimate', :position => 'Shooting Guard', :description => 'The player drives quickly forward before taking a giant step back, ankle breaking a defender in range.', :image => 'link' 
m140 = Move.create :name => 'No Look Step Back', :category => 'Trick, Drive', :position => 'Shooting Guard', :description => 'The player fakes a forward drive before stepping back with a crossover.', :image => 'link'
m141 = Move.create :name => 'Standing Floating 3-pointer', :category => 'Offense, Shoot', :position => 'Shooting Guard', :description => 'When standing outside the 3-point line, the player will be ready to perform a catch and shoot.', :image => 'link'
m142 = Move.create :name => 'Drive and Floater', :category => 'Offense, Shoot', :position => 'Shooting Guard', :description => 'While performing any driving moves, the player can stun his defender with sudden floating jumper.', :image => 'link'
m143 = Move.create :name => 'Full Speed', :category => 'Trick, Speed Up', :position => 'Shooting Guard', :description => "The player's strong will to win allows him to sprint at a faster speed.", :image => 'link' 
m144 = Move.create :name => 'Alright Intercpetion', :category => 'Passive, Intercept', :position => 'Shooting Guard', :description => 'The player can follow an opponent closely and instinctively make an interception when he tries to make a pass.', :image => 'link'
m145 = Move.create :name => 'Windmill Tip-in', :category => 'Ultimate', :position => 'Centre', :description => 'The player jumped up quickly, caught the rebound in the air, and then used the windmill posture to dunk the ball into the basket.', :image => 'link'
m146 = Move.create :name => 'Cut', :category => 'Trick, Move', :position => 'Centre', :description => 'The player uses his mighty strength to shafe off opposing player, and immediately got to the painted area', :image => 'link'
m147 = Move.create :name => 'Build Up Arms Guard', :category => 'Defense, Block', :position => 'Centre', :description => 'tap on the button to let the player build up at the place, to jump higher to block the opponent.', :image => 'link'
m148 = Move.create :name => 'Arm-stretched Rebound', :category => 'Defense, Rebound', :position => 'Centre', :description => 'The player jumped high into the air and spread his long arms to take the rebound directly.', :image => 'link'
m149 = Move.create :name => 'Arm-stretched Rebound', :category => 'Defense, Rebound', :position => 'Centre', :description => 'The player jumped high into the air and spread his long arms to take the rebound directly.', :image => 'link'
m150 = Move.create :name => 'Arm-stretched Rebound', :category => 'Defense, Rebound', :position => 'Centre', :description => 'The player jumped high into the air and spread his long arms to take the rebound directly.', :image => 'link'

#=-=-=-=--=-==-=-=-=-=-=-=-=-= Associations -=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=#

puts "Players and Moves"
p1.moves << m1 << m2 << m3 << m4 << m5 << m6
p2.moves << m7 << m8 << m9 << m10 << m11 << m12
p3.moves << m13 << m14 << m15 << m16 << m17 << m18
p4.moves << m19 << m20 << m21 << m22 << m23 << m24
p5.moves << m25 << m26 << m27 << m28 << m29 << m30
p6.moves << m31 << m32 << m33 << m34 << m35 << m36
p7.moves << m37 << m38 << m39 << m40 << m41 << m42
p8.moves << m43 << m44 << m45 << m46 << m47 << m48
p9.moves << m49 << m50 << m51 << m52 << m53 << m54
p10.moves << m55 << m56 << m57 << m58 << m59 << m60
p11.moves << m61 << m62 << m63 << m64 << m65 << m66
p12.moves << m67 << m68 << m69 << m70 << m71 << m72
p13.moves << m73 << m74 << m75 << m76 << m77 << m78
p14.moves << m79 << m80 << m81 << m82 << m83 << m84
p15.moves << m85 << m86 << m87 << m88 << m89 << m90
p16.moves << m91 << m92 << m93 << m94 << m95 << m96
p17.moves << m97 << m98 << m99 << m100 << m101 << m102
p18.moves << m103 << m104 << m105 << m106 << m107 << m108
p19.moves << m109 << m110 << m111 << m112 << m113 << m114
p20.moves << m115 << m116 << m117 << m118 << m119 << m120
p21.moves << m121 << m122 << m123 << m124 << m125 << m126
p22.moves << m127 << m128 << m129 << m130 << m131 << m132
p23.moves << m133 << m134 << m135 << m136 << m137 << m138
p24.moves << m139 << m140 << m141 << m142 << m143 << m144
p25.moves << m145 << m146 << m147 << m148 << m149 << m150

# puts "Players and Dreams"
# d1.players << p1 << p2 << p3 << p4 << p5
# d2.players << p6 << p7 << p8 << p9 << p10
